### ISSUE TITLE
Use custom Icons according to ports.yml

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/website#47]
The ports.yml allows the Icon field to point to custom SVG Icons instead of a SimpleIcon in case the Icon doesn't exists or isn't suitable. The website should use those Icons. The files exists, they just need to be loaded.

## ToDo

- [x] Create functionality to load custom Icons
- [x] Unify the Icons into a similar format
- [x] Implement custom Icon for `Minecraft`
  - [x] Also PR this to the ports.yml
